# ✅ 1단계: 빌드 스테이지
FROM node:22-alpine AS builder

WORKDIR /app

# 패키지 설치
COPY package*.json ./
RUN npm install

# Prisma schema & 코드 복사 + generate
COPY prisma ./prisma
COPY src ./src
COPY tsconfig.json ./
RUN npx prisma generate
CMD ["npm", "run", "dev"]